from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from sqlalchemy import inspect, text
from sqlalchemy.engine import Connection, Engine

from app.core.aadhaar import tokenize_legacy_aadhaar


@dataclass(frozen=True)
class Migration:
    version: str
    name: str
    up: Callable[[Connection], None]


def _identity_pk(connection: Connection) -> str:
    if connection.dialect.name == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def _bool_default_false(connection: Connection) -> str:
    if connection.dialect.name == "postgresql":
        return "BOOLEAN NOT NULL DEFAULT FALSE"
    return "BOOLEAN NOT NULL DEFAULT 0"


def _exec(connection: Connection, sql: str) -> None:
    connection.execute(text(sql))


def _table_names(connection: Connection) -> set[str]:
    return set(inspect(connection).get_table_names())


def _column_names(connection: Connection, table_name: str) -> set[str]:
    if table_name not in _table_names(connection):
        return set()
    return {column["name"] for column in inspect(connection).get_columns(table_name)}


def _add_column_if_missing(
    connection: Connection,
    table_name: str,
    column_name: str,
    column_definition: str,
) -> None:
    if column_name in _column_names(connection, table_name):
        return
    _exec(connection, f"ALTER TABLE {table_name} ADD COLUMN {column_definition}")


def _drop_column_if_exists(connection: Connection, table_name: str, column_name: str) -> None:
    if column_name not in _column_names(connection, table_name):
        return
    _exec(connection, f"ALTER TABLE {table_name} DROP COLUMN {column_name}")


def _create_schema_migrations(connection: Connection) -> None:
    _exec(
        connection,
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version VARCHAR(20) PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    )


def _migration_001_initial_schema(connection: Connection) -> None:
    pk = _identity_pk(connection)
    is_primary_type = _bool_default_false(connection)

    _exec(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS users (
            id {pk},
            email VARCHAR(100) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            role VARCHAR(20) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ck_users_role CHECK (role IN ('admin','parent'))
        )
        """,
    )
    _exec(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS students (
            id {pk},
            admission_number VARCHAR(20) NOT NULL UNIQUE,
            student_id VARCHAR(20) NOT NULL UNIQUE,
            date_of_birth DATE,
            student_name VARCHAR(100) NOT NULL,
            father_name VARCHAR(100),
            mother_name VARCHAR(100),
            mobile_number VARCHAR(15),
            class_name VARCHAR(10) NOT NULL,
            section VARCHAR(5) NOT NULL,
            student_aadhaar_token VARCHAR(64),
            father_aadhaar_token VARCHAR(64),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    )
    _exec(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS parents (
            id {pk},
            user_id INTEGER NOT NULL,
            student_id INTEGER NOT NULL,
            phone_number VARCHAR(15),
            is_primary {is_primary_type},
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_parents_user_student UNIQUE (user_id, student_id),
            FOREIGN KEY(user_id) REFERENCES users(id),
            FOREIGN KEY(student_id) REFERENCES students(id)
        )
        """,
    )
    _exec(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS fee_structure (
            id {pk},
            student_id INTEGER NOT NULL,
            academic_year VARCHAR(9) NOT NULL,
            admission_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
            term1_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
            term2_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
            term3_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
            transport_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
            books_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
            CONSTRAINT uq_fee_structure_student_year UNIQUE (student_id, academic_year),
            CONSTRAINT ck_fee_structure_non_negative CHECK (
                admission_fee >= 0 AND term1_fee >= 0 AND term2_fee >= 0 AND
                term3_fee >= 0 AND transport_fee >= 0 AND books_fee >= 0
            ),
            FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE
        )
        """,
    )
    _exec(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS concessions (
            id {pk},
            student_id INTEGER NOT NULL,
            academic_year VARCHAR(9) NOT NULL,
            transport_concession NUMERIC(10, 2) NOT NULL DEFAULT 0,
            other_concession NUMERIC(10, 2) NOT NULL DEFAULT 0,
            CONSTRAINT uq_concessions_student_year UNIQUE (student_id, academic_year),
            CONSTRAINT ck_concessions_non_negative CHECK (
                transport_concession >= 0 AND other_concession >= 0
            ),
            FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE
        )
        """,
    )
    _exec(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS payments (
            id {pk},
            student_id INTEGER NOT NULL,
            academic_year VARCHAR(9) NOT NULL,
            fee_head VARCHAR(20) NOT NULL,
            amount_paid NUMERIC(10, 2) NOT NULL,
            payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
            payment_mode VARCHAR(20),
            payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
            razorpay_order_id VARCHAR(50),
            razorpay_payment_id VARCHAR(50),
            receipt_number VARCHAR(30) UNIQUE,
            collected_by VARCHAR(100),
            remarks TEXT,
            CONSTRAINT ck_payments_fee_head CHECK (
                fee_head IN ('term1','term2','term3','transport','books','admission')
            ),
            CONSTRAINT ck_payments_status CHECK (payment_status IN ('pending','success','failed')),
            CONSTRAINT ck_payments_amount_positive CHECK (amount_paid > 0),
            FOREIGN KEY(student_id) REFERENCES students(id)
        )
        """,
    )
    _exec(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id {pk},
            actor_user_id INTEGER,
            actor_email VARCHAR(100),
            action VARCHAR(100) NOT NULL,
            entity_type VARCHAR(50) NOT NULL,
            entity_id VARCHAR(50),
            status VARCHAR(20) NOT NULL DEFAULT 'success',
            ip_address VARCHAR(45),
            details TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
        )
        """,
    )
    _exec(
        connection,
        "CREATE INDEX IF NOT EXISTS ix_payments_student_year_status "
        "ON payments (student_id, academic_year, payment_status)",
    )
    _exec(
        connection,
        "CREATE INDEX IF NOT EXISTS ix_payments_student_year_head_status "
        "ON payments (student_id, academic_year, fee_head, payment_status)",
    )
    _exec(
        connection,
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_razorpay_order_id "
        "ON payments (razorpay_order_id) WHERE razorpay_order_id IS NOT NULL",
    )
    _exec(
        connection,
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_razorpay_payment_id "
        "ON payments (razorpay_payment_id) WHERE razorpay_payment_id IS NOT NULL",
    )
    _exec(
        connection,
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at ON audit_logs (created_at)",
    )
    _exec(
        connection,
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON audit_logs (action)",
    )
    _exec(
        connection,
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_entity ON audit_logs (entity_type, entity_id)",
    )


def _migration_002_tokenize_legacy_aadhaar(connection: Connection) -> None:
    if "students" not in _table_names(connection):
        return

    _add_column_if_missing(connection, "students", "date_of_birth", "date_of_birth DATE")
    _add_column_if_missing(
        connection,
        "students",
        "student_aadhaar_token",
        "student_aadhaar_token VARCHAR(64)",
    )
    _add_column_if_missing(
        connection,
        "students",
        "father_aadhaar_token",
        "father_aadhaar_token VARCHAR(64)",
    )

    columns = _column_names(connection, "students")
    if {"student_aadhaar", "father_aadhaar"} & columns:
        select_columns = ["id"]
        if "student_aadhaar" in columns:
            select_columns.append("student_aadhaar")
        if "father_aadhaar" in columns:
            select_columns.append("father_aadhaar")

        rows = connection.execute(text(f"SELECT {', '.join(select_columns)} FROM students")).mappings()
        for row in rows:
            values: dict[str, str | int | None] = {"id": row["id"]}
            assignments: list[str] = []
            if "student_aadhaar" in row.keys() and row["student_aadhaar"] is not None:
                student_aadhaar_token = tokenize_legacy_aadhaar(row["student_aadhaar"])
                if student_aadhaar_token is not None:
                    values["student_aadhaar_token"] = student_aadhaar_token
                    assignments.append("student_aadhaar_token = :student_aadhaar_token")
            if "father_aadhaar" in row.keys() and row["father_aadhaar"] is not None:
                father_aadhaar_token = tokenize_legacy_aadhaar(row["father_aadhaar"])
                if father_aadhaar_token is not None:
                    values["father_aadhaar_token"] = father_aadhaar_token
                    assignments.append("father_aadhaar_token = :father_aadhaar_token")
            if assignments:
                connection.execute(
                    text(f"UPDATE students SET {', '.join(assignments)} WHERE id = :id"),
                    values,
                )

    _drop_column_if_exists(connection, "students", "student_aadhaar")
    _drop_column_if_exists(connection, "students", "father_aadhaar")
    _exec(
        connection,
        "CREATE INDEX IF NOT EXISTS ix_students_student_aadhaar_token "
        "ON students (student_aadhaar_token)",
    )


MIGRATIONS: tuple[Migration, ...] = (
    Migration("001", "initial_schema", _migration_001_initial_schema),
    Migration("002", "tokenize_legacy_aadhaar", _migration_002_tokenize_legacy_aadhaar),
)


def apply_migrations(engine: Engine) -> None:
    with engine.begin() as connection:
        _create_schema_migrations(connection)
        applied = {
            row[0]
            for row in connection.execute(text("SELECT version FROM schema_migrations")).all()
        }

        for migration in MIGRATIONS:
            if migration.version in applied:
                continue
            migration.up(connection)
            connection.execute(
                text(
                    "INSERT INTO schema_migrations (version, name) "
                    "VALUES (:version, :name)"
                ),
                {"version": migration.version, "name": migration.name},
            )
